### ISSUE TITLE
Feature request: Gradient support

### ISSUE THREAD

**Issue by ArtelGG** [lokka30/MicroLib#19]
I think a welcomed addition to ML would be gradient support.

A project that has gradient support which I find both very robust and easy to work with is [TitleManager](https://www.spigotmc.org/resources/1049/).
The format they use is `%{gradient:[<START HEX>, [OPTIONAL HEX], <END HEX>]<TEXT>}`. Perhaps ML could support something similar.

For example: `%{gradient:[#0080FE, #2792A5, #2792A5, #7C6BEA]Example text}` would look something like this:
![image](https://user-images.githubusercontent.com/21347579/155157695-943863d9-d3e7-4fa6-b55e-776150d176db.png)

**EDIT:** I forgot [MiniMessage](https://github.com/KyoriPowered/adventure) was a thing, that could also be an alternative (much simpler on your end as well).

**Comment by lokka30** [comment]
> I think a welcomed addition to ML would be gradient support.
> 
> A project that has gradient support which I find both very robust and easy to work with is [TitleManager](https://www.spigotmc.org/resources/1049/). The format they use is `%{gradient:[<START HEX>, [OPTIONAL HEX], <END HEX>]<TEXT>}`. Perhaps ML could support something similar.
> 
> For example: `%{gradient:[#0080FE, #2792A5, #2792A5, #7C6BEA]Example text}` would look something like this: ![image](https://user-images.githubusercontent.com/21347579/155157695-943863d9-d3e7-4fa6-b55e-776150d176db.png)
> 
> **EDIT:** I forgot [MiniMessage](https://github.com/KyoriPowered/adventure) was a thing, that could also be an alternative (much simpler on your end as well).

Thanks for the suggestion 😄
Unfortunately I believe I can't maintain such a feature - programming custom gradients are beyond my knowledge to write and make edits to. I also believe MiniMessage and MineDown are awesome libraries that already have solved these requirements. Do you like those libraries?

**Comment by ArtelGG** [comment]
I've used quite a few plugins now which have MiniMessage support and it's been a smooth experience every time. It is very forgiving in regards to how the placeholders are handled and fairly beginner friendly, not to mention the wiki is very solid as well. I didn't know of MineDown before so I can't really comment about that, from a quick gander it seems pretty straight forward, though.

**Comment by lokka30** [comment]
> I've used quite a few plugins now which have MiniMessage support and it's been a smooth experience every time. It is very forgiving in regards to how the placeholders are handled and fairly beginner friendly, not to mention the wiki is very solid as well. I didn't know of MineDown before so I can't really comment about that, from a quick gander it seems pretty straight forward, though.

Awesome to hear! If neither of those solutions work well for you, feel free to open this issue. Again, thank you for bringing forward this suggestion :)

**Comment by ArtelGG** [comment]
I'll try to create a new project which utilizes one of those libraries and see if I can't make a PR to implement them into ML in a manner that would require little to no maintenance.

The biggest challenge with implementing MiniMessage into something like ML is to create methods which handle standard inputs such as a player/command sender, otherwise it would require people to completely rewrite how messages are sent within their entire project due to the requirements of [Audiences](https://docs.adventure.kyori.net/audiences.html) and [Components](https://docs.adventure.kyori.net/text.html).  Outside of that, maintaining an implementation of MiniMessage would be as simple as updating a Maven dependency version.  We'll see how it goes.
